name: expenses_tracker
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^14.8.1
  provider: ^6.1.2
  fl_chart: ^0.70.2
  sqflite: ^2.4.2
  path: ^1.9.1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  rxdart: ^0.28.0
  fluttertoast: ^8.2.12
  flutter_native_splash: ^2.4.5
  carousel_slider: ^5.0.0
  shared_preferences: ^2.2.2
  google_sign_in: ^6.3.0
  path_provider: ^2.1.2
  uuid: ^4.3.3
  connectivity_plus: ^5.0.2
  cloud_firestore: ^5.6.6
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite_common_ffi: ^2.3.0
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
